version: '3.8'

services:
  rtmp-streamer:
    build: .
    ports:
      - "80:80"      # HTTP
      - "1935:1935"  # RTMP
      - "8080:8080"  # Auth server
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance
      - ./logs:/var/log     # Agregar volumen para logs
      - ./static:/app/static  # Agregar volumen para archivos estáticos
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - TZ=America/Los_Angeles  # Zona horaria
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
