"""Agregar campo repeat_interval

Revision ID: 3b37a77a893a
Revises: fff60fdb2478
Create Date: 2025-01-11 13:41:02.915571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b37a77a893a'
down_revision = 'fff60fdb2478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_interval', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.drop_column('repeat_interval')

    # ### end Alembic commands ###
