"""Agregar campo repeat_type

Revision ID: 6f8e903de7e7
Revises: 7ee96c54f60a
Create Date: 2025-01-11 15:04:22.158662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8e903de7e7'
down_revision = '7ee96c54f60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_type', sa.String(length=20), nullable=True))
        batch_op.drop_column('repeat_interval')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_interval', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('repeat_type')

    # ### end Alembic commands ###
