"""Eliminar campo max_plays

Revision ID: 7ee96c54f60a
Revises: 3b37a77a893a
Create Date: 2025-01-11 14:01:28.356649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee96c54f60a'
down_revision = '3b37a77a893a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.drop_column('max_plays')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_plays', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
