"""Initial migration

Revision ID: 950f363e64de
Revises: 
Create Date: 2025-01-10 02:09:00.582113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950f363e64de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_params', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.drop_column('video_params')

    # ### end Alembic commands ###
