"""Add is_active field

Revision ID: 978a4ff2700b
Revises: 
Create Date: 2025-01-09 22:55:41.190275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978a4ff2700b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('input_path', sa.String(length=500), nullable=False),
    sa.Column('output_rtmp', sa.String(length=500), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream')
    # ### end Alembic commands ###
