"""Agregar campo max_plays

Revision ID: fff60fdb2478
Revises: 950f363e64de
Create Date: 2025-01-10 02:16:03.528968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff60fdb2478'
down_revision = '950f363e64de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_plays', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.drop_column('max_plays')

    # ### end Alembic commands ###
